### ISSUE TITLE
false positive for CSS Grid 'fr' unit

### ISSUE THREAD

**Issue by orzechowskid** [JulianSSS/stylelint-no-magic-numbers#4]
**Describe the bug**
I am receiving a false positive when linting rules which use the CSS Grid `fr` unit.

**To Reproduce**
with the following stylelint config:

```json
{
  "plugins": [
    "stylelint-magic-numbers"
  ],
  "rules": {
    "magic-numbers/magic-numbers": [
      true,
      {
        "acceptedNumbers": [ 0 ],
        "acceptedValues": [ "100%", "1fr" ],
        "severity": "error"
      }
    ]
  }
}
```

run `stylelint` against the following css:

```css
.example {
  display: grid;
  grid-template-rows: max-content 1fr max-content;
}
```

**Expected behavior**
expected linting to succeed

**Error Logs**

**Desktop (please complete the following information):**
node 12.18.3

**Additional context**

I believe this would be solved by updating `valueRegExp` here to include `fr`: https://github.com/JuStTheDev/stylelint-magic-numbers/blob/master/src/index.js#L39

**Comment by JuStTheDev** [comment]
Hi @orzechowskid,

I just published your solution to this issue to npm and pushed it here.
Here https://github.com/JuStTheDev/stylelint-magic-numbers/commit/1659544c334f9b109fe06a89747e8e9e8327eca4 wrote some additional testing for the new unit.

See you!
